pipeline {
    agent any 
    
    stages { 
        stage('SCM Checkout') {
            steps {
                retry(3) {
                    checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/WishyCode/DevOps_Sample.git']])
                }
            }
        }
        stage('Build Docker Image') {
            steps {  
                bat """
                cd GitHub-Docker-and-Jenkins-CI-CD-Pipeline
                docker build -t wishydocker/mydockerapp:%BUILD_NUMBER% .
                """
            }
        }
        stage('Login to Docker Hub') {
            steps {
                withCredentials([string(credentialsId: 'docker-password-id', variable: 'dockerpassword')]) {
                    script {
                        bat "docker login -u wishydocker -p %dockerpassword%"
                    }
                }
            }
        }
        stage('Push Image') {
            steps {
                bat 'docker push wishydocker/mydockerapp:%BUILD_NUMBER%'
            }
        }
    }
    post {
        always {
            bat 'docker logout'
        }
    }
}